import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Results'
import requests from '../utils/requests'

const Home: NextPage = ({
  results,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Results results={results} />
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const genre = context.query.genre || 'fetchTrending'
  const request = await fetch(`
  https://api.themoviedb.org/3${requests[genre as string].url}
  `).then((response) => response.json())

  return {
    props: {
      results: request.results,
    },
  }
}

export default Home
